name: Dart Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the beta Docker image
      run: cd beta/buster && docker build . --file Dockerfile
    - name: Build the stable Docker image
      run: cd stable/buster && docker build . --file Dockerfile
